#!/bin/sh
[ "$DEBUG" ] && set -x
set -e

if [ -f "/image" ] && [ "$(cat /image)" = "pages" ]; then
  echo "Github does not allow user dependencies."
  exit 0
fi

strip_jekyll() {
  if grep -qE "gem\s*(\"|')jekyll(\"|')" Gemfile; then
    sed -ri "/^gem\s+(\"|')jekyll\1.*$/d" \
      Gemfile
  fi
}

cd /srv/jekyll
if [ "$FORCE_APK_INSTALL" ]; then
  install_user_pkgs_from_file
fi

bundle_cmd() {
  ruby -e '
    comp = ARGV[1..-1]
    comp.include?("bundle") && comp.include?(ARGV[0]) \
      ? exit(0) : exit(1)
  ' "$@"
}

if ([ -f "Gemfile" ] || bundle_cmd "bundle", "$@") && ! bundle_cmd "update" "$@" \
    && ! bundle_cmd "install" "$@" && ! bundle_cmd "clean" "$@"; then
  chpst -u jekyll:jekyll docker-helper \
    install_users_gems
fi
