#!/bin/bash
set -e
set -x

JEKYLL_DOCKER_TAG=${JEKYLL_DOCKER_TAG-"jekyll/jekyll"}
docker build --no-cache --force-rm -t ${JEKYLL_DOCKER_TAG}:stable .
docker run --rm -v $(pwd):/srv/jekyll -it ${JEKYLL_DOCKER_TAG}:stable buildeb

if [[ ! -z "${JEKYLL_BETA_VERSION}" ]]
then
  sed -r "s/(ENV JEKYLL_VERSION=).*/\1${JEKYLL_BETA_VERSION}/" Dockerfile > beta.dockerfile
  docker build --no-cache --force-rm -f beta.dockerfile -t ${JEKYLL_DOCKER_TAG}:beta .
  docker run --rm -v $(pwd):/srv/jekyll -it ${JEKYLL_DOCKER_TAG}:beta buildeb
  rm beta.dockerfile
fi
