name: 'Pull'
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    name: 'Build'
    strategy:
      matrix:
        env:
          - jekyll:latest
          - builder:latest
          - minimal:latest
          - jekyll:pages
    steps:
      - uses: actions/checkout@v3
      - name: 'Setup Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle install
      - run: |
          echo $'{\n    "experimental": true\n}' | \
            sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
        name: 'docker experimental'
      - run: docker-template build $DOCKER_REPO --no-push --force --squash
        env:
          RUBYOPT: "-W0"
          DOCKER_REPO: "${{join(matrix.env, ' ')}}"
