#!/bin/bash -e

if [[ "$#" -gt 1 ]]
then
  echo "We only accept a single path."
  exit 1
elif [[ ! -z "$1" ]]
then
  if [[ -d "$1" ]]
    then export PATH=$1:$PATH
  else
    echo "It seems that the path your provided is invalid."
    exit 1
  fi
fi

yes | gem update --no-document
yes | gem update --system --no-document

if echo $JEKYLL_VERSION | grep -qP '^git@'
then
  cd /usr/src
  version=$(echo $JEKYLL_VERSION | sed -r 's/^git@//')
  git clone --depth 1 --single-branch --branch="$version" \
    https://github.com/jekyll/jekyll.git
  cd jekyll

  rake build
  gem install pkg/jekyll-*.gem --no-document
  rm -rf /usr/src/jekyll
else
  yes | gem install jekyll -v \
    ${JEKYLL_VERSION} --no-document
fi

cd ~
for g in $(cat /usr/share/jekyll/gems); do
  if echo $g | grep -q "@"
  then
    yes | gem install --no-document \
         "$(echo $g | awk -F@ '{ print $1 }')" \
      -v "$(echo $g | sed -r 's/[^@]+@(.*)/\1/')"
  else
    yes | gem install "$g" --no-document
  fi
done

gem clean
rm -rf /opt/jekyll/lib/ruby/gems/$RUBY_VERSION/cache/*
rm -rf    /usr/lib/lib/ruby/gems/$RUBY_VERSION/cache/*
rm -rf ~/.gem
