#!/bin/bash

if [[ -f /srv/docker/Gemfile.docker ]]
then
  echo "Moving Gemfile.docker back to Gemfile"
  echo "I hope you did not have a Gemfile actually called that."
  mv /srv/docker/Gemfile.docker /srv/docker/Gemfile
fi
