#!/bin/sh
[ "$DEBUG" ] && set -x
set -e

#

if [ -f "/image" ] && [ "$(cat /image)" = "pages" ]; then
  echo "Github does not allow user dependencies."
  exit 0
fi

#

cd /srv/jekyll
if [ "$FORCE_APK_INSTALL" ]
  then docker-helper install_user_pkgs_from_file
fi

#

chpst -u jekyll:jekyll docker-helper \
  install_users_gems
