#!/bin/bash -l
[ "$DEBUG" ] && set -x
set -e

IMAGE=${IMAGE:-"jekyll/jekyll"}
docker system prune -f

latest=$(ruby -e '
  require "yaml"
  $stdout.puts YAML.load_file("opts.yml")["tags"].keys.sort.keep_if { |v|
    v =~ /[0-9]\./
  }.last
')

docker rmi "$IMAGE:$latest" $IMAGE:latest || true
bundle exec docker-template build "$IMAGE:$latest" $IMAGE:latest --no-push
docker run --rm -it "$IMAGE:$latest" bash
