#!/bin/sh
root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
$root/script/sync
set -e

if [ $# -eq 1 ] && [ -d "$root/images/$1" ]; then
  cd $root/images/$1
  docker build -t \
    jekyll/$1 .

elif [ $# -gt 0 ]; then
  >&2 echo "Bad Image"
  exit 1
else
  for v in $root/versions/*; do
    script/build "$(basename "$v")"
  done
fi
