#!/bin/sh
root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
repo="$(cd $root; basename "$(pwd)")"
set -e

if [ $# -eq 2 ]; then
  user=$1; shift
   tag=$1; shift

elif [ $# -eq 1 ]; then
  user=${DOCKER_USER:-jekyll}
   tag=$1; shift

elif [ $# -gt 0 ]; then
  echo "Too many arguments, only one..two accepted."
  exit 1
fi

cd $root
script/sync
if [ "$tag" ] && [ -d "tags/$tag" ]; then
  cd tags/$tag
  image=$user/$repo:$tag
  printf "Building the image %s\n" $image
  docker build -t $image .
  tput clear || true
elif [ $# -gt 1 ]; then
  >&2 echo "Too many tags given, only one accepted."
  exit 1
else
  for v in options/versions/*; do
    $0 "$(basename $v)"
  done
fi
