#!/bin/sh

# ----------------------------------------------------------------------------
# Make sure we have a recent version of Docker.
# ----------------------------------------------------------------------------

sudo apt-get update
sudo apt-get upgrade --assume-yes $(dpkg --get-selections |grep docker | awk '{ print $1 }')
sudo service restart docker

# ----------------------------------------------------------------------------

bundle exec docker-template build --no-diff --no-push \
  --no-cache --no-clean
