#!/bin/sh

# --
# Make sure we have a recent version of Docker.
sudo apt-get update sudo apt-get update >/dev/null
sudo apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
  --assume-yes --only-upgrade docker docker-engine

sudo mkdir -p /etc/docker
printf "{\n  \"experimental\": true\n}" | sudo tee /etc/docker/daemon.json
sudo service docker restart

# --

status=0
bundle exec docker-template build $DOCKER_REPO || status=$?
if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$status" -eq 0 ]
  then bundle exec docker-template push \
    $DOCKER_REPO

else
  exit 1
fi
