#!/bin/bash -l
set -e

IMAGE=${IMAGE:-"jekyll/jekyll"}
docker system prune -f

latest=$(ruby -e '
  require "yaml"
  $stdout.puts YAML.load_file("opts.yml")["tags"].keys.sort.keep_if { |v|
    v =~ /[0-9]\./
  }.last
')

VERSION=${VERSION:-$latest}
docker rmi "$IMAGE:$VERSION" || true
bundle exec docker-template build "$IMAGE:$VERSION" --no-push
docker run --rm -it "$IMAGE:$VERSION" bash
