#!/bin/bash -l
[ "$DEBUG" = "true" ] && set -x
set -e

if [ "$CI" = "true" ]; then
  sudo apt-get update \
    -o Dir::Etc::sourceparts="-" \
    -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/docker.list" \
    -o APT::Get::List-Cleanup="0"

  sudo apt-get install \
    --assume-yes --only-upgrade \
    -o Dpkg::Options::="--force-confdef" \
    -o Dpkg::Options::="--force-confold" \
    docker docker-engine

  sudo mkdir -p /etc/docker
  # We need experimental so we can squash our images.
  printf "{\n  \"experimental\": true\n}\n" | sudo tee /etc/docker/daemon.json
  sudo service docker restart
fi
