#!/bin/sh

[ "$DEBUG" ] && set -x
user=${DOCKER_USER:-jekyll}
root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
repo=${DOCKER_REPO:-jekyll}
set -e

cd $root
if [ $# -eq 1 ] && [ -d "images/$1" ]; then
  docker pull "$user/$repo:$1"
elif [ $# -gt 0 ]; then
  echo "Bad Tag"
  exit 1
else
  for v in images/*; do
    $0 "$(
      basename $v
    )"
  done
fi
