#!/bin/sh

[ "$DEBUG" ] && set -x
user=${DOCKER_USER:-jekyll}
root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
repo=$(basename $root)
set -e

cd $root
for v in images/*; do
  docker pull "$user/$repo:$(
    basename $v
  )"
done
