#!/bin/sh
[ "$DEBUG" ] && set -x
root=$(cd "$(dirname "$(readlink -f $0)")/.."; pwd)
yml=script/yml
set -e

cd $root
if [ $# -eq 1 ] && [ -f "vendor/sync/$1" ]; then
  sync=$1 && shift
  exec "vendor/sync/$sync" \
    "$@"

elif [ $# -gt 0 ]; then
  >&2 echo "Unknown Image."
  exit 1
else
  mkdir -p tags
  rm -rf tags/*

  for v in  $($yml -k versions); do
    version=$($yml versions.$v)
    mkdir -p tags/$v
    tag=tags/$v

    [ -f .dockerignore ] && cp .dockerignore $tag/.dockerignore
    cp copy -R $tag/copy

    mkdir -p $tag/copy/usr/share/ruby
    gems=$($yml gems.$v)
    [ "$gems" ] || gems=$($yml gems.all)
    echo $gems > $tag/copy/usr/share/ruby/default-gems
    erb "version=$version" "type=$v" Dockerfile > $tag/Dockerfile
    cp README.md $tag/README.md
  done
fi
