#!/bin/sh
set -e

if [ -f /etc/service/nginx/error ]; then
  echo "Refusing to start, there was an Nginx error."
  sleep 300
  exit 1
else
  echo "Starting Nginx on port 80 for Jekyll via /srv/jekyll/_site"
  echo "You should forgo using 'jekyll s' and use 'jekyll w'"
  exec nginx || touch /etc/service/nginx/error
fi
