#!/usr/bin/env ruby

# -----------------------------------------------------------------------------
# I don't want to hear your bitching about how this fucks with your shit
# because it works for me, and if it works for me it must work for you but
# seriously, it does not stop you from using -H and -s again - override.
# That is exactly why I put it at the top and not the bottom but tbh
# if you override you are on your own, I'll raise my hands and walk away.
# -----------------------------------------------------------------------------

if %W(s serve server).include?(ARGV[0])
  ARGV.unshift(ARGV.shift,
    "-H", "0.0.0.0", "-s", "/srv/jekyll"
  )
else
  ARGV.unshift(ARGV.shift,
    "-s", "/srv/jekyll"
  )
end

# Dropping the mic and walking out.
load Gem.bin_path("jekyll", "jekyll")
