#!/usr/bin/env bash
[[ "$debug" ]] && set -x
set -e

stable=$(gem search jekyll | grep --color=never -E '^jekyll\s+\(.*\)' | sed -r 's/^jekyll\s+\((.*)\)$/\1/')
beta=$(gem search jekyll --pre | grep --color=never -E '^jekyll\s+\(.*\)' | sed -r 's/^jekyll\s+\((.*)\)$/\1/' | awk -F', ' '{ print $1 }')
pages=$(curl -vs https://pages.github.com/versions.json 2>/dev/null | ruby \
  -rjson -e '$stdout.puts JSON.parse($stdin.gets)["jekyll"];')

printf "jekyll@%s" $pages  > versions/pages
printf "jekyll@%s" $stable > versions/stable
printf "jekyll@%s" $beta   > versions/beta
echo "Gem versions have been updated."
script/sync
