name: 'Push'

on:
  push:
    branches:
      - $default-branch
  schedule:
    - cron: 2 4 10 * *

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    name: 'Build'
    strategy:
      fail-fast: true
      matrix:
        variant: [jekyll, builder, minimal]
        main_tag: [latest, pages]
        include:
          - main_tag: latest
            tags: |
              latest,priority=900
              4.2.2,priority=700
              4.2,priority=500
              4,priority=300
              stable,priority=100
          - main_tag: pages
            tags: pages

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2'
          bundler-cache: true

      - name: Generate Dockerfiles
        env:
          RUBYOPT: "-W0"
        run: |
          gem install docker-template
          docker-template cache

      - name: Set Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: jekyll/${{ matrix.variant }}
          flavor: latest=false
          tags: ${{ matrix.tags }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./repos/${{ matrix.variant }}/cache/${{ matrix.main_tag }}
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
            linux/s390x
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: "--squash"
