name: 'Push'
on:
  push:
    branches:
      - $default-branch
  schedule:
    - cron: 2 4 10 * *
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    name: 'Build'
    strategy:
      fail-fast: false
      matrix:
        env:
          -
            - jekyll:4.3.2
            - jekyll:stable
            - jekyll:latest
            - jekyll:4.0
            - jekyll:4
          -
            - builder:4.3.2
            - builder:stable
            - builder:latest
            - builder:4.0
            - builder:4
          -
            - minimal:4.3.2
            - minimal:stable
            - minimal:latest
            - minimal:4.0
            - minimal:4
          - builder:pages
          - minimal:pages
          - jekyll:pages
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - run: bundle install

      - run: |
          echo $'{\n    "experimental": true\n}' | \
            sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
        name: 'docker experimental'

      - name: 'docker login'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: bundle exec docker-template build $DOCKER_REPO --no-push --force --squash
        env:
          RUBYOPT: "-W0"
          DOCKER_REPO: "${{ join(matrix.env, ' ') }}"

      - run: bundle exec docker-template push $DOCKER_REPO
        env:
          RUBYOPT: "-W0"
          DOCKER_REPO: "${{ join(matrix.env, ' ') }}"
