name: 'Push'
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    name: 'Build'
    strategy:
      fail-fast: false
      matrix:
        env:
          -
            - jekyll:4.0.1
            - jekyll:stable
            - jekyll:latest
            - jekyll:4.0
            - jekyll:4
          -
            - builder:4.0.1
            - builder:stable
            - builder:latest
            - builder:4.0
            - builder:4
          -
            - minimal:4.0.1
            - minimal:stable
            - minimal:latest
            - minimal:4.0
            - minimal:4
          - builder:pages
          - minimal:pages
          - jekyll:pages
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - run: bundle install
      - run: |
          echo $'{\n    "experimental": true\n}' | \
            sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
        name: 'docker experimental'
      - name: 'docker login'
        run: |
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login \
            --username ${{secrets.DOCKER_USERNAME}} \
            --password-stdin
      - run: |
          docker-template build $DOCKER_REPO --no-push --force --squash
          docker-template push  $DOCKER_REPO
        env:
          RUBYOPT: "-W0"
          DOCKER_REPO: "${{join(matrix.env, ' ')}}"
