name: Docker Image CI

on:
  pull_request:
    branches: $default-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build . --file repos/builder/Dockerfile --tag jv-conseil/jekyll-docker:$(date +%s)
      
    - name: Docker Push
      run: docker push jv-conseil/jekyll-docker
